### ISSUE TITLE
* Error running Gradle: ProcessException: Process android\gradlew.bat" exited abnormally:

### ISSUE THREAD

**Issue by pratiktimer** [sarbagyastha/youtube_player#1]
> Configure project :screen
WARNING: The specified Android SDK Build Tools version (25.0.3) is ignored, as it is below the minimum supported version (27.0.3) for Android Gradle Plugin 3.1.2.
Android SDK Build Tools 27.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '25.0.3'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

**Comment by sarbagyastha** [comment]
prariktimer, either remove buildToolsVersion '25.0.3' from your app level build.gradle 
or, replace 25.0.3 with 27.0.3

**Comment by sarbagyastha** [comment]
@pratiktimer  either remove buildToolsVersion '25.0.3' from your app level build.gradle
or, replace 25.0.3 with 27.0.3
