### ISSUE TITLE
Unable to use this Plugin

### ISSUE THREAD

**Issue by ghost** [sarbagyastha/youtube_player#10]
Launching lib\main.dart on SM J500F in debug mode...
D:\CURRENT\qw\android\app\src\main\AndroidManifest.xml:6:9-27 Error:
	Attribute application@label value=(qw) from AndroidManifest.xml:6:9-27
	is also present at [com.github.HaarigerHarald:android-youtubeExtractor:master-SNAPSHOT] AndroidManifest.xml:15:9-41 value=(@string/app_name).
	Suggestion: add 'tools:replace="android:label"' to <application> element at AndroidManifest.xml:4:5-23:19 to override.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@label value=(testingapproject) from AndroidManifest.xml:6:9-27
  	is also present at [com.github.HaarigerHarald:android-youtubeExtractor:master-SNAPSHOT] AndroidManifest.xml:15:9-41 value=(@string/app_name).
  	Suggestion: add 'tools:replace="android:label"' to <application> element at AndroidManifest.xml:4:5-23:19 to override.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by sarbagyastha** [comment]
@rajeshjeshar Add `tools:replace="android:label"` to your Manifest file as shown in the screenshot.

![image](https://user-images.githubusercontent.com/9782008/52194321-67425680-287b-11e9-9724-8a2de9b2e012.png)
