### ISSUE TITLE
Example doesn't run on Android 7.0 (power 2)

### ISSUE THREAD

**Issue by willvlad** [sarbagyastha/youtube_player#11]
Gradle task 'assembleDebug'...
AGPBI: {"kind":"error","text":"Invoke-customs are only supported starting with Android O (--min-api 26)","sources":[{}],"tool":"D8"}
AGPBI: {"kind":"error","text":"Invoke-customs are only supported starting with Android O (--min-api 26)","sources":[{}],"tool":"D8"}
AGPBI: {"kind":"error","text":"Invoke-customs are only supported starting with Android O (--min-api 26)","sources":[{}],"tool":"D8"}
AGPBI: {"kind":"error","text":"Default interface methods are only supported starting with Android N (--min-api 24): void com.google.android.exoplayer2.Player$EventListener.onLoadingChanged(boolean)","sources":[{}],"tool":"D8"}
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by sarbagyastha** [comment]
@willvlad updated the example. Try rebuilding with the newer source. 😊
