### ISSUE TITLE
VideoPlayerController, can no longer be used Error. [3.0.2]

### ISSUE THREAD

**Issue by Y-ndm** [sarbagyastha/youtube_player#12]
Hello there.. 
Well right after i go from one page to another calling (Navigator.of(context).pushReplacement())... the Debug Console gives me this error.

`I/flutter (19833): ══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY ╞════════════════════════════════════════════════════════
I/flutter (19833): The following assertion was thrown while dispatching notifications for VideoPlayerController:
I/flutter (19833): 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3473 pos 12:
I/flutter (19833): '_debugLifecycleState != _ElementLifecycle.defunct': is not true.
I/flutter (19833): 
I/flutter (19833): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (19833): more information in this error message to help you determine and fix the underlying cause.
I/flutter (19833): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (19833):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (19833): .......`

I think it has something to do with VideoPlayerController. I've tried defining (CallbackController) with a VideoPlayerController _controller;.. But it doesn't seem to fix the issue. the app doesn't crash or stop it just pauses and you have to click on the play button on the debugger to keep scrolling through the app.

**Comment by PembaDomaSherpa** [comment]
Will look into the issue tonight. For now, you could try disposing the controller(obtained through callbackController) just before navigating to another page and see if it works.

**Comment by sarbagyastha** [comment]
Closing as there is no response from the Author.
