### ISSUE TITLE
No background overlay appeared in version 2.0.3

### ISSUE THREAD

**Issue by ljfreelancer88** [sarbagyastha/youtube_player#14]
I tried both Asus and LG phone but the background overlay is not working when I tap play and pause of video.

**Comment by sarbagyastha** [comment]
@ljfreelancer88 could you provide me with code snippet, how you're implementing background overlay ?

**Comment by ljfreelancer88** [comment]
I just added the `controlsBackgroundColor: Color.fromRGBO(255, 0, 0, 0.7)` in VideoPlayer. I'm expecting a background that covers all the screen with less opacity but the result is, the background is only for controller.

The behavior in YouTube. If you tap the pause on the screen. It will have a black background with less opacity. It will not disappear unless you tap and play again the video. :)

**Comment by sarbagyastha** [comment]
@ljfreelancer88 Added on new version.

**Comment by ljfreelancer88** [comment]
Is it 3.1.0 or ^3.0.1? :) Because I can't install when I use your 3.1.0 version but it works when I use the 3.0.1 version.

**Comment by sarbagyastha** [comment]
@ljfreelancer88 currently working on **3.1.0**, it's not yet published to Dart Pub.

**Comment by sarbagyastha** [comment]
@ljfreelancer88 Uploaded it on pub, you can now use **[v3.1.0](https://pub.dartlang.org/packages/youtube_player)**

**Comment by ljfreelancer88** [comment]
Thank you so much. Based on the new update. These are my observation based on UI perspective. 
1. When i pause the video, the background overlay appeared but in just a few seconds it will disappear. The background overlay should remain, until it presses again the play.
2. Since you have now the "double tap" for forward and backward, it would be better to show also an icon for that when I press the play/pause so that the user(kids, old folk or non-tech user) will know the feature. :)

**Comment by sarbagyastha** [comment]
Thank you for your feedbacks. 😊 In next update timeOut for controls/overlay property will be added. As per the second point, you could notify user with the feature as Youtube does. Also there is a press-n-hold gesture to get to fullscreen.
