### ISSUE TITLE
Can I run in full-screen mode at startup?

### ISSUE THREAD

**Issue by kyungjoongo** [sarbagyastha/youtube_player#16]
Can I run in full-screen mode at startup?

**Comment by sarbagyastha** [comment]
@kyungjoongo the feature was causing bug so was removed. It will be added in future releases.

**Comment by sarbagyastha** [comment]
@kyungjoongo Added the feature in **[v3.1.0](https://pub.dartlang.org/packages/youtube_player)**

**Comment by kyungjoongo** [comment]
@sarbagyastha thank you~!
