### ISSUE TITLE
stream error 

### ISSUE THREAD

**Issue by offbrok** [sarbagyastha/youtube_player#2]
i can't paste youtube stream, you can fix it?

Syncing files to device Android SDK built for x86...
I/flutter (21140): built
I/flutter (21140): sxPwMuMSzUM
I/flutter (21140): sxPwMuMSzUM
D/        (21140): HostConnection::get() New Host Connection established 0xe4ecd2c0, tid 21159
D/EGL_emulation(21140): eglMakeCurrent: 0xdd7a8960: ver 3 1 (tinfo 0xdd8693a0)
I/flutter (21140): built
I/flutter (21140): sxPwMuMSzUM
I/flutter (21140): sxPwMuMSzUM
I/System.out(21140): Keeping screen on 
W/nockknock.knoc(21140): Accessing hidden method Landroid/media/AudioTrack;->getLatency()I (light greylist, reflection)
I/ExoPlayerImpl(21140): Init dae21cf [ExoPlayerLib/2.9.1] [generic_x86, Android SDK built for x86, Google, 28]
D/NetworkSecurityConfig(21140): No Network Security Config specified, using platform default
W/VideoCapabilities(21140): Unrecognized profile 4 for video/hevc
I/VideoCapabilities(21140): Unsupported profile 4 for video/mp4v-es
I/OMXClient(21140): IOmx service obtained
D/SurfaceUtils(21140): connecting to surface 0xc3f5c008, reason connectToSurface
I/MediaCodec(21140): [OMX.google.h264.decoder] setting surface generation to 21647361
D/SurfaceUtils(21140): disconnecting from surface 0xc3f5c008, reason connectToSurface(reconnect)
D/SurfaceUtils(21140): connecting to surface 0xc3f5c008, reason connectToSurface(reconnect)
E/ACodec  (21140): [OMX.google.h264.decoder] setPortMode on output to DynamicANWBuffer failed w/ err -1010
I/ACodec  (21140): codec does not support config priority (err -1010)
I/OMXClient(21140): IOmx service obtained
I/ACodec  (21140): codec does not support config priority (err -2147483648)
I/ACodec  (21140): codec does not support config operating rate (err -2147483648)
D/MediaCodec(21140): [OMX.google.h264.decoder] setting dataspace on output surface to #103
W/MapperHal(21140): buffer descriptor with invalid usage bits 0x2000
D/        (21140): HostConnection::get() New Host Connection established 0xc531cd80, tid 21180
D/SoftwareRenderer(21140): setting dataspace on output surface to #103
W/MapperHal(21140): buffer descriptor with invalid usage bits 0x2000
W/MapperHal(21140): buffer descriptor with invalid usage bits 0x2000
W/MapperHal(21140): buffer descriptor with invalid usage bits 0x2000
I/OMXClient(21140): IOmx service obtained
I/ACodec  (21140): codec does not support config priority (err -2147483648)
I/ACodec  (21140): codec does not support config operating rate (err -2147483648)

**Comment by offbrok** [comment]
youtube stream works here https://pub.dartlang.org/packages/flutube

**Comment by sarbagyastha** [comment]
@offbrok  I am working on it, will update the plugin by tomorrow.

**Comment by offbrok** [comment]
@sarbagyastha thanks.
