### ISSUE TITLE
Is this approach of playing youtube videos against youtube policy?

### ISSUE THREAD

**Issue by Er-rchydy** [sarbagyastha/youtube_player#20]
I want to use this plugin to play some youtube videos in my app, but i want to ask first if this approach is against youtube policy because i'll add admob ads to my app.
thanks for the great plugin

**Comment by ljfreelancer88** [comment]
I want to know this as well.

**Comment by sarbagyastha** [comment]
Here we're simply using the Youtube's web service as the javascript api does. So it shouldn't be against the policy. As per the [TOS](https://www.youtube.com/static?template=terms) , distribution and commercialization of YouTube service is restricted. So, if you intend to add admob I think you shouldn't place both ad and player on the same screen. Same applies for the official youtube player api [_REFERENCE  1_](https://stackoverflow.com/questions/36031019/ads-admob-in-android-app-using-youtube-api) [_REFERENCE 2_](https://productforums.google.com/forum/#!msg/adsense/N1LNsbOIVmk/8dD7HKRNBQAJ)

**Comment by Er-rchydy** [comment]
ok thanks for the information
