### ISSUE TITLE
Can't play some video Ids. Source error and a http 403 exception.

### ISSUE THREAD

**Issue by jorg1piano** [sarbagyastha/youtube_player#22]
Some ids doesn't load an results in the exo player throwing a http 403 exception

For example I can get this videoId to run: nQtQyhPAm0w 
But not this: 1k8craCGpgs

The error is the same in the 'Youtube Player Demo' application as in my own app.

`E/BufferQueueProducer( 9696): [] Can not get hwsched service
I/ExoPlayerImpl( 9696): Init 438f7fe [ExoPlayerLib/2.9.6] [HWFIG-H, FIG-LX1, HUAWEI, 26]
I/YoutubePlayerPlugin( 9696): Quality: 240p WEBM
I/YoutubePlayerPlugin( 9696): Media Type: GENERAL
E/ExoPlayerImplInternal( 9696): Source error.
E/ExoPlayerImplInternal( 9696): com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
E/ExoPlayerImplInternal( 9696):         at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:300)
E/ExoPlayerImplInternal( 9696):         at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
E/ExoPlayerImplInternal( 9696):         at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:885)
E/ExoPlayerImplInternal( 9696):         at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
E/ExoPlayerImplInternal( 9696):         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
E/ExoPlayerImplInternal( 9696):         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
E/ExoPlayerImplInternal( 9696):         at java.lang.Thread.run(Thread.java:784)`

**Comment by sarbagyastha** [comment]
Some copyrighted videos have problem while extracting its media source. Since the plugin is based on extracted media source, so it might not play such videos. Currently working on new approach of implementing the player plugin, which will get published soon if everything goes as planned.

**Comment by jorg1piano** [comment]
Today I retried the videoids I mentioned and now they played back just fine. Not sure if its helpful. Thanks for the great work your doing on this plugin :)

**Comment by sarbagyastha** [comment]
New plugin [**youtube_player_flutter**](https://pub.dartlang.org/packages/youtube_player_flutter) is published with iOS support and improved playback & controls. Do checkout. 🙂

**Comment by ljfreelancer88** [comment]
Great news. How about migrating from `youtube_player` to `youtube_player_flutter`? Does it need some extra work or cleanup?

If we publish an app using `youtube_player_flutter` (in an iframe). There's no "foul" to YouTube and Apple?

**Comment by sarbagyastha** [comment]
@ljfreelancer88 , not much work on migration, you can change few properties and you'll be good to go. 

Yup, there won't be any foul as it's official way of playing YouTube videos in web and Apple OS family.
