### ISSUE TITLE
Exiting full screen if i long press the slider

### ISSUE THREAD

**Issue by shiva2562** [sarbagyastha/youtube_player#26]
I am using this player for my app,when i play a video in full screen mode and if i long press(for 2 secs or so) the slider head,the player is exiting its full screen mode and going back to normal mode.

Slider head,By that i mean the the thing i circled in the image
![slider](https://user-images.githubusercontent.com/38890114/55795622-e48d8000-5ae5-11e9-949e-9e20582d7e64.jpeg)

**Comment by sarbagyastha** [comment]
Actually it's an intensional feature(tap and hold to enter/exit fullscreen). Although will make it optional in next update.

**Comment by sarbagyastha** [comment]
[**Version 3.2.1**](https://pub.dartlang.org/packages/youtube_player#-changelog-tab-) is published. And long tap to fullscreen is disabled by default.

**Comment by shiva2562** [comment]
Thank you so much
