### ISSUE TITLE
Could you add 144p resolution support?

### ISSUE THREAD

**Issue by alexjuniodev** [sarbagyastha/youtube_player#27]
I think you should change only 

`enum YoutubeQuality { LOWEST, LOW, MEDIUM, HIGH, HD, FHD }`

AND 

```
  String qualityMapping(YoutubeQuality quality) {
    switch (quality) {
      case YoutubeQuality.LOWEST:
        return '144p';
      case YoutubeQuality.LOW:
        return '240p';
      case YoutubeQuality.MEDIUM:
        return '360p';
      case YoutubeQuality.HIGH:
        return '480p';
      case YoutubeQuality.HD:
        return '720p';
      case YoutubeQuality.FHD:
        return '1080p';
      default:
        return "Invalid Quality";
    }
  }
```

**Comment by sarbagyastha** [comment]
Thanks for your suggestion, will work on it. But changing these only ain't enough as the plugin is dependent on Android side. Changing these only will play videos in 720p although you select 144p.

**Comment by sarbagyastha** [comment]
@alexjuniodev, [Version 3.2.2](https://pub.dartlang.org/packages/youtube_player#-changelog-tab-) adds supports for 144p playback. 🍻
