### ISSUE TITLE
onVideoEnded is not firing

### ISSUE THREAD

**Issue by ljfreelancer88** [sarbagyastha/youtube_player#28]
When i drag the "circle play indicator" until it almost finishes the video, the `onVideoEnded` is not firing. It only fires when you play the video without skipping. 

Because what I want to do is when the video finished. It will prompt a custom widget, let say an alert or a repeat or back button.

**Comment by sarbagyastha** [comment]
@ljfreelancer88 , [Version 3.2.2](https://pub.dartlang.org/packages/youtube_player#-changelog-tab-) fixes the issue with `onVideoEnded`.
