### ISSUE TITLE
Video does not stops when we press back button

### ISSUE THREAD

**Issue by ParthAggarwal1996** [sarbagyastha/youtube_player#3]
import 'package:flutter/material.dart';
import 'package:youtube_player/youtube_player.dart';

class YTPlayer extends StatefulWidget {
  final String videoID;
  YTPlayer({this.videoID});
  @override
  _YTPlayerState createState() => _YTPlayerState();
}

class _YTPlayerState extends State<YTPlayer> {
  Widget youtubeplay() => YoutubePlayer(
        source: widget.videoID,
        quality: YoutubeQuality.HD,
        aspectRatio: 16 / 9,
        showThumbnail: true,
        bufferedColor: Colors.grey,
        playedColor: Colors.blue,
        loop: false,
      );

  @override
  void dispose() {
    super.dispose();
    youtubeplay();
  }

  @override
  Widget build(BuildContext context) => Scaffold(
        appBar: AppBar(
          title: Text('Player'),
        ),
        body: Container(
          child: Column(
            children: <Widget>[
              Card(
                child: Center(
                  child: youtubeplay(),
                ),
              )
            ],
          ),
        ),
      );
}

**Comment by sarbagyastha** [comment]
@ParthAggarwal1996 , your issue has been addressed with Patch Version [0.6.1](https://pub.dartlang.org/packages/youtube_player#-changelog-tab-) . Please confirm if it is fixed or not and do let me know.
