### ISSUE TITLE
Video plays from the beginning when device change orientation

### ISSUE THREAD

**Issue by ljfreelancer88** [sarbagyastha/youtube_player#30]
Hi, the video plays from the beginning when the device changed orientation. 

You can make all these issues as reference for testing to your new `youtube player` package :)

**Comment by sarbagyastha** [comment]
It's working fine in my case. Is it an issue in youtube_player_flutter package ?

**Comment by sarbagyastha** [comment]
#29

**Comment by sarbagyastha** [comment]
#29
