### ISSUE TITLE
Video have incorrect progress position after orientation was changed

### ISSUE THREAD

**Issue by jmas** [sarbagyastha/youtube_player#31]
**Steps to reproduce:**
1. Start playing video
2. Change orientation to Full Screen
3. Change orientation back
4. See that progress bar is stop change value (it stopped change value following the video)

**Expected result:**
1. Progress bar working correctly after orientation change

**Comment by sarbagyastha** [comment]
**Acknowledged**

**Comment by sarbagyastha** [comment]
[Version 3.4.1](https://pub.dartlang.org/packages/youtube_player#-changelog-tab-) fixes the issue. 🍻

**Comment by jmas** [comment]
@sarbagyastha Wow, thank you! Tested and looks fixed.
