### ISSUE TITLE
Unable to load a video

### ISSUE THREAD

**Issue by nitishpatel** [sarbagyastha/youtube_player#36]
LOGS`D/EgretLoader( 7486): EgretLoader(Context context)
D/EgretLoader( 7486): The context is not activity
I/YoutubePlayerPlugin( 7486): Quality: 720p WEBM
I/YoutubePlayerPlugin( 7486): Media Type: GENERAL
E/ExoPlayerImplInternal( 7486): Source error.
E/ExoPlayerImplInternal( 7486): com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
E/ExoPlayerImplInternal( 7486):         at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:300)
E/ExoPlayerImplInternal( 7486):         at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
E/ExoPlayerImplInternal( 7486):         at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:885)
E/ExoPlayerImplInternal( 7486):         at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
E/ExoPlayerImplInternal( 7486):         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
E/ExoPlayerImplInternal( 7486):         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
E/ExoPlayerImplInternal( 7486):         at java.lang.Thread.run(Thread.java:764)
I/zygote64( 7486): Do full code cache collection, code=250KB, data=179KB
I/zygote64( 7486): After code cache collection, code=250KB, data=161KB
`
Also This is the video link:[https://www.youtube.com/watch?v=NHr6lTKYCNc](url)
This is video never runs

**Comment by bkoruznjak** [comment]
Getting the same error for every video I have tried so far.

Nexus 5x, Android 8.0.1
Flutter 1.5.4-hotfix.2

**Comment by sarbagyastha** [comment]
The plugin doesn't support some protected videos. It's kind of a limitation.
