### ISSUE TITLE
_resolutionBottomSheet Bottom Overflowed

### ISSUE THREAD

**Issue by uisuru** [sarbagyastha/youtube_player#40]
![Screenshot_20190624-220630](https://user-images.githubusercontent.com/23442915/60036401-c7238780-96cc-11e9-9ebb-38a2e38681d0.png)

**Comment by uisuru** [comment]
It works when you change 
Container(
                    height: 30,
                    width: 30,
                  ),
to
FittedBox(
                  fit: BoxFit.fill,
                  child: Container(
                      height: MediaQuery.of(context).size.height/(6*4),
                      width: MediaQuery.of(context).size.width,
                    ),
                  )

**Comment by uisuru** [comment]
Change _qualityRow
```
             Container(
                  height: 30,
                    width: 30,
                  ),
```
to 
```
              Container(
                  height: _qualityRow_height,
                  width: 30,
                ),
```

in Widget build
```
  Widget build(BuildContext context) {
    _qualityrow_height = MediaQuery.of(context).size.height/(24); 
```

**Comment by sarbagyastha** [comment]
Should be fixed in new version
