### ISSUE TITLE
MissingPluginException(No implementation found for method init on channel sarbagyastha.com.np/youtubePlayer

### ISSUE THREAD

**Issue by imsujan276** [sarbagyastha/youtube_player#41]
Youtube Video Id: 7QUtEmBT_-w
E/flutter ( 8842): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method init on channel sarbagyastha.com.np/youtubePlayer)
E/flutter ( 8842): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:300:7)

**Comment by andreadelfante** [comment]
Same issue here

**Comment by SteadyAction** [comment]
same

**Comment by BRLOKESH** [comment]
Same here

**Comment by sarbagyastha** [comment]
Does the issue persists after full restarting application ?

**Comment by BRLOKESH** [comment]
LOKESH:~ LOKESH$ touch /.bash_profile
LOKESH: LOKESH$ open -e /.bash_profile
LOKESH: LOKESH$ source $HOME/.bash_profile
LOKESH:~ LOKESH$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Server.app/Contents/ServerRoot/usr/bin:/Applications/Server.app/Contents/ServerRoot/usr/sbin:/Users/apple/Desktop/flutter V1.5.4/flutter/bin:/Users/apple/Desktop/flutter V1.5.4/bin
LOKESH:~ LOKESH$

**Comment by sarbagyastha** [comment]
Full rebuild will fix the problem

**Comment by anybao** [comment]
This issue is still present when I restart the application or do a full rebuild. Please help me!

**Comment by alwinlazar** [comment]
Same here
