### ISSUE TITLE
Cannot get video length, stream state and other properties?

### ISSUE THREAD

**Issue by AxDSan** [sarbagyastha/youtube_player#6]
I noticed in the README, in the Future versions we will have `High level of customization` but I'm not sure what does that means, is it regarding UI customization or internals?

Anyways, my concern comes mainly after trying to see if I could access properties of the video/stream e.g. Get current video playback time, get video length, get video player state (playing, stopped, paused) etc., etc.

Is there any possibility that we could have these implementations done?

Thanks for looking into this request.
___
Up to mention that I'm new to Flutter and to Dart... if this is possible to achieve already, could you please provide me with a code sample?

**Comment by sarbagyastha** [comment]
@AxDSan , I'm revamping the plugin currently, working to address the problems you mentioned. 😊

**Comment by sarbagyastha** [comment]
@AxDSan , **[v 0.8.0](https://pub.dartlang.org/packages/youtube_player#-changelog-tab-)** might meet your requirements.

**Comment by AxDSan** [comment]
Thank you so much!
