### ISSUE TITLE
An issue with the player on 0.7.2 .. "the method was called on null"

### ISSUE THREAD

**Issue by Y-ndm** [sarbagyastha/youtube_player#7]
After updating the player to V.0.7.2 the app would show me an error on the screen.
"NosuchMethodError: The method 'call' was called on null.
I/flutter ( 5688): Receiver: null
I/flutter ( 5688): Tried calling: call(Instance of 'YoutubePlayerController')"

And on the Debug console 
"
`I/flutter ( 5688): #397    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.attachRootWidget 
package:flutter/…/widgets/binding.dart:712
I/flutter ( 5688): #398    runApp 
package:flutter/…/widgets/binding.dart:756
I/flutter ( 5688): #399    main 
package:yt_demo/main.dart:6
I/flutter ( 5688): #400    _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
I/flutter ( 5688): #401    _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
I/flutter ( 5688): ════════════════════════════════════════════════════════════════════════════════════════════════════`
"

it looks like the error is caused by this line in the youtube_player.dart (
` widget.callbackController(_youtubePlayerControllerController);` Line: 820
).

After i comment the line the error goes away but the player and the app in general start to behave in a weird way.. for instance. the player won't dispose when i leave the current page and the video would take alot of time to start.
Hope you can fix this issue.

P.S. i have updated directly from 0.6.1 to 0.7.2 .. by changing the plugin number in "pubspec.yaml" and right after that it started to show me this error.

**Comment by Y-ndm** [comment]
![screenshot_1548714035](https://user-images.githubusercontent.com/46603925/51870272-611c1980-2353-11e9-974d-3c5e880eb66e.png)

Here's a screenshot of what shows up  on the screen.

**Comment by Y-ndm** [comment]
The problem was fixed by adding a YoutubePlayerController but in general, the app now is a chaos.. this update is so bad, unfortunately.. the 0.6.1 was so stable.. now after a hot reload it plays a  video on top of the one playing so you have two videos playing at the same time and if you navigate into another page the video doesn't dispose nore pause and when you exit the page the video in it won't dispose either and you'll have 3 videos playing at the same time.
I hope that you go back to 0.6.1 update and only fix the video loading issue (make it faster cause it's the only thing that i think is necessary) as for the YoutubePlayerController i think is unnecessary and before the plugin worked just like a charm without it.

**Comment by sarbagyastha** [comment]
@Y-ndm , Thank you for reporting issue. Updated the plugin to **[v0.8.0](https://pub.dartlang.org/packages/youtube_player#-changelog-tab-)**. Please do report whether or not the issue is fixed properly.

**Comment by Y-ndm** [comment]
It's seems all working just fine.
One quetion though .. is there anyway to get the video's thumbnail link so it can be stored??.
I know it does show up but is there any way to like store it in a String so it can be uploaded.

Thanks for the great work  sarbagyastha.

**Comment by sarbagyastha** [comment]
You're most welcome @Y-ndm . Refer to [this](https://stackoverflow.com/questions/2068344/how-do-i-get-a-youtube-video-thumbnail-from-the-youtube-api) .

**Comment by Y-ndm** [comment]
0.8.0 still showing some weird behaviours.. 
_you can't pause/play from a button unless you play another URL (from a button) then you can pause/play.
_if you change the player's container size (onClick = change height size) before the video plays then it will play two videos on top of each other and if you exit the page one video will still be playing.

So far these are the two issue that I ran through in 0.8.0 still playing with it.

**Comment by sarbagyastha** [comment]
@Y-ndm , try the new update **v0.8.1**

**Comment by Y-ndm** [comment]
Great job all good. BUT when it comes to videos in portrait mode they still don't work properly.. the video stretches instead of showing in portrait mode. 
Still having fun with it and trying to see if i'll discover more. I think there's something with FloatingActionButton when you exit the page.. but it showes only in DebugConsole. i'll let you know.

**Comment by sarbagyastha** [comment]
@Y-ndm can you share the screenshot with streching video ? And the resolution of the device you're using.

**Comment by Y-ndm** [comment]
check out this clip and see how the video is in portrait mode. "https://www.youtube.com/watch?v=beg_zjKeCBA".

Here's how it looks like on my emulator. 
![screenshot_1548848122](https://user-images.githubusercontent.com/46603925/51978849-af343880-248b-11e9-926b-5ca77b089efa.png)

the same thing happens when i test on my LG m250n.

**Comment by sarbagyastha** [comment]
Are having the problem with only portait videos ?

**Comment by Y-ndm** [comment]
Yes portrait mode only.. i've tryied other non 16/9 videos and they work just fine.

![screenshot_1549019824](https://user-images.githubusercontent.com/46603925/52120025-5d221d00-261b-11e9-80ad-82e4408e7175.png)

**Comment by sarbagyastha** [comment]
Will look out for the solution @Y-ndm . And will update plugin with the solution.
