### ISSUE TITLE
Disable autoplay

### ISSUE THREAD

**Issue by dasmikko** [sarbagyastha/youtube_player#8]
How can i disable auto playing?

It doesn't seem to be documented.

**Comment by PembaDomaSherpa** [comment]
@dasmikko autoPlay was mistakenly removed in newer versions, will add it by today.

**Comment by dasmikko** [comment]
I just went through the commits, and it was removed in 0.6.1.

**Comment by ljfreelancer88** [comment]
Same here.

**Comment by sarbagyastha** [comment]
@dasmikko @ljfreelancer88 , Added autoPlay property in **v1.0.1**

**Comment by ljfreelancer88** [comment]
Wow! Thank you. Appreciate your help. I'll test on my end right away. 
Just a little favor, maybe update also the snippet codes on the documentation about the new autoPlay property.

**Comment by ljfreelancer88** [comment]
After my upgrade to **v1.0.1**. The `placeHolder` property wasn't existed anymore w/c not a big deal for me. But the `autoPlay` property still wasn't available for use.

**Comment by ljfreelancer88** [comment]
Fixes for **v1.0.1** works! Thank You again.

**Comment by sarbagyastha** [comment]
Sure @ljfreelancer88
