### ISSUE TITLE
Play and pause on video screen

### ISSUE THREAD

**Issue by ljfreelancer88** [sarbagyastha/youtube_player#9]
Hi,

The default player has only have play button on the middle of the screen. Can we have also the pause on middle of the screen. Since these two are the common features and to be more efficient.

Thank you

**Comment by sarbagyastha** [comment]
@ljfreelancer88 , I'm working on to imitating the controls of default youtube player. Thanks for your kin suggestion. 😊

**Comment by sarbagyastha** [comment]
@ljfreelancer88 , redesigned the plugin at version 2.0.2 , check it out.
